name: Docker Image CI

env:
  IMAGE_NAME: fca
  IMAGE_TAG: ${{github.run_number}}

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        environment: AzureUSGovernment
        creds: ${{ secrets.AZ_CREDS }}
    
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt
    - run: pytest -vv


    #Security Check - Bandit
    - uses: actions/checkout@v2
    - name: Security check - Bandit
      uses: ioggstream/bandit-report-artifacts@v0.0.2
      with:
        project_path: .
        ignore_failure: true

    - name: Security check report artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Security report
        path: output/security_report.txt

    # Code Coverage
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }} 


    #Docker Login
    - name: Docker Images Build And Push
      uses: azure/docker-login@v1
      with:
        login-server: flaskdemoacr.azurecr.us # default: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t flaskdemoacr.azurecr.us/fca:${{github.run_number}} -t flaskdemoacr.azurecr.us/fca:latest
        docker push flaskdemoacr.azurecr.us/fca:${{github.run_number}}
        docker push flaskdemoacr.azurecr.us/fca:latest
    
    #Container Scan
    - name: Container Scan
      uses: azure/container-scan@v0
      with:
        image-name: flaskdemoacr.azurecr.us/fca:${{github.run_number}} # ${{ env.loginServerUrl }}/ would be empty if it's hosted on dockerhub; ${{ github.sha }} could also be replaced with any desired image tag
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    #SBOM
    - name: Anchore SBOM
      uses: anchore/sbom-action@v0
      with:
        image: flaskdemoacr.azurecr.us/fca # ${{ env.loginServerUrl }}/ would be empty if it's hosted on docke
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}

    #Deploy ACI
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: aks
        dns-name-label: flaskacidemo
        image: flaskdemoacr.azurecr.us/fca:${{github.run_number}}
        registry-login-server: flaskdemoacr.azurecr.us
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: democi
        location: 'east us2'
